name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java (If needed for your project)
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Set the Java version that your project uses
          distribution: ''

      - name: Build Project (e.g., Maven)
        run: mvn clean install  # Adjust this command to your build tool (e.g., Maven, Gradle)

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t my-image:latest .

      - name: Tag Docker Image
        run: |
          REPOSITORY_URI=${{ secrets.ECR_REGISTRY }}/my-image
          docker tag my-image:latest $REPOSITORY_URI:latest

      - name: Push Docker Image to ECR
        run: |
          REPOSITORY_URI=${{ secrets.ECR_REGISTRY }}/my-image
          docker push $REPOSITORY_URI:latest
